/// Flutter icons FunIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FunIcons
///      fonts:
///       - asset: fonts/FunIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FunIcons {
  FunIcons._();

  static const _kFontFam = 'FunIcons';
  static const _kFontPkg = null;

  static const IconData chart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warningSign = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verticalArrows = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
